

front:	
	cd front && cmake -B ../build/front -G "Visual Studio 15 2017 Win64" 

back:
	cd back  && cmake -B ../build/back  -G "Visual Studio 15 2017 Win64" 

model:
	cd model && cmake -B ../build/model -G "Visual Studio 15 2017 Win64" 

mon:	
	cd vsmon && cmake -B ../build/vsmon -G "Visual Studio 15 2017 Win64" 
	
#	cd vsmon && cmake -B ../build/vsmon   -G "Visual Studio 16 2019" 